### ISSUE TITLE
SSL検証で死ぬっぽい

### ISSUE THREAD

**Issue by tuyapin** [tuyapin/Snowfox#12]
https://github.com/tuyapin/Snowfox/commit/229fc77925f305ce62e77b5e63f22529d76d8d97
一時的にSSL証明書の検証を無効化した。

**Comment by tuyapin** [comment]
https://github.com/tuyapin/Snowfox/commit/742e9a1325210d7190d133fefc57a86ee1c90cf1
私のWindowsが悪いのか？

**Comment by hinaloe** [comment]
うちの窓もぽよ

**Comment by tuyapin** [comment]
＼(^o^)／ｵﾜﾀ

**Comment by tuyapin** [comment]
https://api.croudia.com/statuses/update.json
net.tuyapin.croudia.exception.CroudiaNetworkException: An error occurred in HTTP POST with OAuth2 credentials.
	at net.tuyapin.croudia.CroudiaCredentials.httpPostWithOAuthAsync(CroudiaCredentials.java:309)
	at net.tuyapin.croudia.Statuses.updateStatus(Statuses.java:246)
	at net.tuyapin.snowfox.controllers.MainWindowController.lambda$doTweet$10(MainWindowController.java:375)
	at net.tuyapin.snowfox.controllers.MainWindowController$$Lambda$337/2057570100.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: java.net.ConnectException: https://api.croudia.com:443
	at com.ning.http.client.providers.netty.future.NettyResponseFuture.abort(NettyResponseFuture.java:229)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:107)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.operationComplete(NettyConnectListener.java:115)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409)
	at org.jboss.netty.channel.DefaultChannelFuture.addListener(DefaultChannelFuture.java:145)
	at com.ning.http.client.providers.netty.request.NettyRequestSender.sendRequestWithNewChannel(NettyRequestSender.java:284)
	at com.ning.http.client.providers.netty.request.NettyRequestSender.sendRequestWithCertainForceConnect(NettyRequestSender.java:140)
	at com.ning.http.client.providers.netty.request.NettyRequestSender.sendRequest(NettyRequestSender.java:115)
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.execute(NettyAsyncHttpProvider.java:87)
	at com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java:486)
	at com.ning.http.client.AsyncHttpClient$BoundRequestBuilder.execute(AsyncHttpClient.java:229)
	at net.tuyapin.croudia.CroudiaCredentials.httpPostWithOAuthAsync(CroudiaCredentials.java:301)
	... 6 more
Caused by: java.net.ConnectException: https://api.croudia.com:443
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:103)
	... 16 more
Caused by: java.lang.NullPointerException
	at com.ning.http.client.SSLEngineFactory$DefaultSSLEngineFactory.newSSLEngine(SSLEngineFactory.java:49)
	at com.ning.http.client.providers.netty.channel.ChannelManager.createSslHandler(ChannelManager.java:399)
	at com.ning.http.client.providers.netty.channel.SslInitializer.connectRequested(SslInitializer.java:44)
	at org.jboss.netty.channel.SimpleChannelDownstreamHandler.handleDownstream(SimpleChannelDownstreamHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54)
	at org.jboss.netty.handler.codec.http.HttpClientCodec.handleDownstream(HttpClientCodec.java:97)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
	at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleDownstream(ChunkedWriteHandler.java:109)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582)
	at org.jboss.netty.channel.Channels.connect(Channels.java:634)
	at org.jboss.netty.channel.AbstractChannel.connect(AbstractChannel.java:216)
	at org.jboss.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
	at org.jboss.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at com.ning.http.client.providers.netty.request.NettyRequestSender.connect(NettyRequestSender.java:371)
	at com.ning.http.client.providers.netty.request.NettyRequestSender.sendRequestWithNewChannel(NettyRequestSender.java:283)
	... 12 more

**Comment by tuyapin** [comment]
Closed https://github.com/AsyncHttpClient/async-http-client/issues/839

**Comment by tuyapin** [comment]
他所のIssueも、相手側へ通知が飛ぶとはしらなかった。
> Elsewhere Issue also, did not run a notification to the other side fly.
